Repository operate-first/community-handbook, pull requests merged in 2021-07, with the labels that each got.

#1 Created issue templates for missing and poor documentation
  .github/ISSUE_TEMPLATE/missing-documentation.md
  .github/ISSUE_TEMPLATE/poor-documentation.md
Labels: lgtm, size/M

#3 Adding repo owners to the approvers list
  OWNERS
Labels: approved, area/contributor, kind/handbook, lgtm, size/XS

#4 Updated readme
  README.md
Labels: approved, area/contributor, kind/handbook, lgtm, size/M

#7 Renamed template files
  .github/ISSUE_TEMPLATE/missing_documentation.md
  .github/ISSUE_TEMPLATE/poor_documentation.md
Labels: approved, area/contributor, kind/handbook, lgtm, size/XS

#5 Adding guidelines for content reviewers
  handbook_reviewer_guidelines.md
Labels: approved, area/contributor, kind/handbook, lgtm, size/S

#8 Update issue templates
  .github/ISSUE_TEMPLATE/missing-documentation.md
  .github/ISSUE_TEMPLATE/poor-documentation.md
Labels: approved, lgtm, size/M

#12 Temp reduction for bootstrapping repo
  OWNERS
Labels: approved, lgtm, size/S

#11 How to for using (new) community-centric labels
  content/how-to-use-community-centric-labels.md
Labels: approved, lgtm, size/M

#9 How-to for using `o1-clone` mini tool
  content/how-to-use-o1-clone-tool.md
Labels: approved, area/contributor, kind/handbook, lgtm, size/M

#10 Updates to readme/reviewer_guidelines and new request-repo guide
  README.md
  handbook_reviewer_guidelines.md
  request_a_repository.md
Labels: approved, area/contributor, kind/handbook, lgtm, size/M

#17 Cleanup of files, templates, and organization
  .github/ISSUE_TEMPLATE/missing-documentation.md
  .github/ISSUE_TEMPLATE/missing_documentation.md
  .github/ISSUE_TEMPLATE/poor_documentation.md
  README.md
  content/how-to-request-a-repository.md
  content/request-a-repository.md
  contributing/handbook-reviewer-guidelines.md
Labels: approved, area/contributor, kind/handbook, lgtm, size/M

#19 Added style guide
  contributing/style-guide.md
Labels: approved, lgtm, size/L

#21 Beginners guide
  contributing/beginners-get-started.md
Labels: approved, lgtm, size/M
